# include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.widgetbook.dart"
  errors:
    invalid_annotation_target: ignore