name: groceries_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  intl: ^0.17.0

  cupertino_icons: ^1.0.0
  dropdown_search: ^5.0.2
  uuid: ^3.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  google_fonts: ^3.0.1
  flutter_typeahead: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  widgetbook_annotation: ^2.0.1
  device_frame: ^1.0.0
  
dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.1.5
  very_good_analysis: ^3.0.1
  widgetbook: 2.4.1
  widgetbook_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true

  