name: groceries_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  cloud_firestore: ^2.5.3
  dropdown_search: ^0.6.3
  provider: ^5.0.0
  firebase_core: ^1.6.0
  freezed_annotation: ^0.14.3
  uuid: ^3.0.4
  widgetbook: ^0.0.9
  storybook_flutter: ^0.7.0+1
  dashbook: ^0.1.4
  storyboard: ^1.0.0
  flutterbook: ^0.1.3
  

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^5.0.2

flutter:
  uses-material-design: true