import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:groceries_app/models/ingredient.dart';

part 'recipe.freezed.dart';
part 'recipe.g.dart';

@freezed
//indicates that this class will be generated by freezed
class Recipe with _$Recipe {
  //_$Recipe is also freezed specific
  factory Recipe({
    //factory is also freezed specific
    String? id,
    required String title,
    required DateTime createdAt,
    @Default(const <Ingredient>[]) List<Ingredient> ingredients,
    //@Default allows to give a default value. Here, an empty List
  }) = _Recipe;

  factory Recipe.fromJson(Map<String, dynamic> json) => _$RecipeFromJson(json);
  //constructor that asks json_serializable to generate the necessary fromJson / toJson
}
