name: Build 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Build Website
        run: flutter build web -t lib/main.widgetbook.dart

      - name: Upload Widgetbook
        uses: widgetbook/widgetbook-hosting@0.0.10
        with:
          path: 'build/web'
          api_key: 'e5OwqJ3-2bPhV1mRdYW-0d2IIPSN0VcqN7FRg4AV_lHSB6S3S2H3hjirHcm6qPm3oghyovMHlphnFbpJIHfIcQ=='