name: Build 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/test_app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Build Website
        run: flutter build web -t lib/main.dart

      - name: Upload Widgetbook
        uses: widgetbook/widgetbook-hosting@0.0.17
        with:
          path: 'apps/test_app/build/web12'
          api_key: 'HHz_3q7-bXzhW62MxSfBPRMxxSuiqJE-vJhag-QPWG-w0c1nmNUoTbpbBuUh0SZfrK-AoucaoiKN3wLCb7xbRw=='
